# Generated by Django 5.2.10 on 2026-03-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Producent')),
                ('website', models.URLField(blank=True, verbose_name='Strona WWW')),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa produktu')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (PLN)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Ilość w magazynie')),
                ('technical_specs', models.JSONField(blank=True, default=dict, verbose_name='Specyfikacja techniczna')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizacja')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Kategoria')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.manufacturer', verbose_name='Producent')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d', verbose_name='Plik obrazu')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Tekst alternatywny')),
                ('main_photo', models.BooleanField(default=False, verbose_name='Główne zdjęcie?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Zdjęcie produktu',
                'verbose_name_plural': 'Galeria zdjęć',
            },
        ),
    ]
