# Generated by Django 5.2.10 on 2026-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Przyjęte do realizacji'), ('processing', 'W trakcie realizacji'), ('shipped', 'Wysłane'), ('completed', 'Zrealizowane'), ('cancelled', 'Anulowane')], default='new', max_length=20),
        ),
    ]
