# Generated by Django 6.0.3 on 2026-05-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cloudtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudTest',
        ),
    ]
