# Generated by Django 6.0.3 on 2026-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_cloudtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
