# Generated by Django 5.2.10 on 2026-04-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_options_alter_productimage_options_and_more'),
        ('main', '0004_product_battery_product_cpu_product_gpu_product_ram_and_more'),
    ]

    operations = [
    ]
