# Generated by Django 6.0.3 on 2026-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
