# Generated by Django 6.0.3 on 2026-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Kurier do domu'), ('pickup_point', 'Punkt Odbioru')], default='courier', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Punktu Odbioru'),
        ),
    ]
