# Generated by Django 6.0.3 on 2026-05-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_delivery_method_order_pickup_point_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres punktu odbioru'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Kurier do domu'), ('pickup_point', 'Punkt odbioru')], default='courier', max_length=20),
        ),
    ]
