# Generated by Django 6.0.3 on 2026-05-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_pickup_point_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firma (sieć) punktu'),
        ),
    ]
