# Generated by Django 6.0.3 on 2026-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_wishlisted_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł slajdu')),
                ('description', models.TextField(verbose_name='Opis slajdu')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Obraz slajdu')),
                ('link', models.URLField(blank=True, verbose_name='Link docelowy')),
            ],
            options={
                'verbose_name': 'Slajd na stronie głównej',
                'verbose_name_plural': 'Slajdy na stronie głównej',
                'ordering': ['id'],
            },
        ),
    ]
