# Generated by Django 6.0.3 on 2026-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_heroslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order'], 'verbose_name': 'Slajd na stronie głównej', 'verbose_name_plural': 'Slajdy na stronie głównej'},
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='link',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy aktywny?'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link przycisku'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejność wyświetlania'),
        ),
    ]
