# Generated by Django 5.1.15 on 2026-05-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_heroslide_options_remove_heroslide_link_and_more'),
        ('main', '0009_merge_20260523_0801'),
    ]

    operations = [
    ]
