# Generated by Django 6.0.3 on 2026-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_paid_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe (Nieopłacone)'), ('paid', 'Opłacone (Do realizacji)'), ('processing', 'W trakcie realizacji'), ('shipped', 'Wysłane'), ('completed', 'Zrealizowane'), ('cancelled', 'Anulowane')], default='new', max_length=20),
        ),
    ]
