# Generated by Django 5.1.15 on 2026-05-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20260530_0642'),
        ('main', '0011_alter_order_status'),
    ]

    operations = [
    ]
